---
- name: Versiones OPNsense firewall
  hosts: opnsense
  become: true
  gather_facts: false

  tasks:

  - name: Guardar versión OPNSense
    ansible.builtin.shell: opnsense-version
    register: result

  - name: Registrar versión OPNSense
    ansible.builtin.debug:
      msg: "Host: {{ inventory_hostname }} - {{ (result.stdout }}"

